//! `exo init` — coding-optimized vessel bootstrap (E10-S2, W-101).

use std::io::Write;
use std::path::{Path, PathBuf};

use exoskeleton_host::config::CodingDefaults;

use crate::client::CliError;

/// Run the `exo init` command.
pub async fn run_init(
    output_path: Option<String>,
    mission: Option<String>,
) -> Result<(), CliError> {
    let cwd = std::env::current_dir()
        .map_err(|e| CliError::Other(format!("cannot determine current directory: {e}")))?;

    let workspace_root = detect_git_root(&cwd).unwrap_or(cwd);
    let repo_name = workspace_root
        .file_name()
        .map(|name| name.to_string_lossy().to_string())
        .unwrap_or_else(|| "project".into());
    let mission = mission.unwrap_or_else(|| format!("Coding assistant for {repo_name}"));

    let exo_dir = workspace_root.join(".exo");
    std::fs::create_dir_all(&exo_dir)
        .map_err(|e| CliError::Other(format!("cannot create {}: {e}", exo_dir.display())))?;

    let config_path = output_path
        .map(PathBuf::from)
        .unwrap_or_else(|| exo_dir.join("vessel.toml"));
    if let Some(parent) = config_path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| CliError::Other(format!("cannot create {}: {e}", parent.display())))?;
    }

    let analysis = exoskeleton_host::kernel::repo_analysis::analyze_repo(&workspace_root);
    let analysis_rendered = analysis.render();
    if !analysis_rendered.is_empty() {
        let instructions_path = exo_dir.join("instructions.md");
        let mut file = std::fs::File::create(&instructions_path)
            .map_err(|e| CliError::Other(format!("cannot write instructions: {e}")))?;
        writeln!(file, "{analysis_rendered}")
            .map_err(|e| CliError::Other(format!("cannot write instructions: {e}")))?;
    }

    let inner_loop =
        CodingDefaults::inner_loop_config(Some(workspace_root.to_string_lossy().to_string()));

    let toml_content = format!(
        r#"# Exoskeleton vessel configuration — generated by `exo init`
# Coding-optimized defaults for {repo_name}

[vessel]
mission = {mission}
data_dir = {data_dir}

[inner_loop]
enabled = true
max_steps_per_tick = {max_steps}
max_tokens_per_session = {max_tokens}
timeout_secs = {timeout_secs}
context_window_size = {context_window_size}
doom_loop_threshold = {doom_loop_threshold}
workspace_root = {workspace_root}

[tool_policy]
default = "allow"

[tool_policy.rules]
"shell.exec" = "ask"
"fs.write" = "ask"
"#,
        repo_name = repo_name,
        mission = quote_toml_string(&mission),
        data_dir = quote_toml_string(&exo_dir.join("data").to_string_lossy()),
        max_steps = inner_loop.max_steps_per_tick,
        max_tokens = inner_loop.max_tokens_per_session,
        timeout_secs = inner_loop.timeout_secs,
        context_window_size = inner_loop.context_window_size,
        doom_loop_threshold = inner_loop.doom_loop_threshold,
        workspace_root =
            quote_toml_string(inner_loop.workspace_root.as_deref().unwrap_or_default(),),
    );

    std::fs::write(&config_path, toml_content)
        .map_err(|e| CliError::Other(format!("cannot write {}: {e}", config_path.display())))?;

    eprintln!("wrote {}", config_path.display());
    if !analysis_rendered.is_empty() {
        eprintln!("wrote {}", exo_dir.join("instructions.md").display());
    }
    eprintln!("start with: exo start --config {}", config_path.display());
    Ok(())
}

fn detect_git_root(start: &Path) -> Option<PathBuf> {
    let output = std::process::Command::new("git")
        .args(["rev-parse", "--show-toplevel"])
        .current_dir(start)
        .output()
        .ok()?;

    if !output.status.success() {
        return None;
    }

    let root = String::from_utf8_lossy(&output.stdout).trim().to_string();
    (!root.is_empty()).then(|| PathBuf::from(root))
}

fn quote_toml_string(s: &str) -> String {
    format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detect_git_root_in_repo() {
        let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        let root = detect_git_root(&manifest_dir);
        assert!(root.is_some());
    }

    #[test]
    fn detect_git_root_in_non_repo() {
        let dir = tempfile::tempdir().unwrap();
        let root = detect_git_root(dir.path());
        assert!(root.is_none());
    }

    #[test]
    fn quote_toml_simple() {
        assert_eq!(quote_toml_string("hello"), "\"hello\"");
    }

    #[test]
    fn quote_toml_with_backslash() {
        assert_eq!(
            quote_toml_string("C:\\Users\\test"),
            "\"C:\\\\Users\\\\test\""
        );
    }
}
