//! Identity types for Exoskeleton.
//!
//! Six UUID-based newtypes generated by `define_id!` plus one content-addressed
//! type ([`ArtifactId`]).

use std::fmt;
use std::str::FromStr;

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use uuid::Uuid;

/// Define a UUID-based identity newtype.
///
/// Generates a struct wrapping [`Uuid`] with `Default`, `new()`, `From<Uuid>`,
/// `AsRef<Uuid>`, `Display`, and `FromStr` implementations. Serializes
/// transparently as a bare UUID string in JSON.
macro_rules! define_id {
    ($name:ident, $doc:expr) => {
        #[doc = $doc]
        #[derive(
            Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize,
        )]
        #[serde(transparent)]
        pub struct $name(Uuid);

        impl Default for $name {
            fn default() -> Self {
                Self::new()
            }
        }

        impl $name {
            /// Create a new random identity.
            pub fn new() -> Self {
                Self(Uuid::new_v4())
            }

            /// Create from a known UUID (for deterministic built-in identifiers).
            pub const fn from_uuid(uuid: Uuid) -> Self {
                Self(uuid)
            }
        }

        impl From<Uuid> for $name {
            fn from(uuid: Uuid) -> Self {
                Self(uuid)
            }
        }

        impl AsRef<Uuid> for $name {
            fn as_ref(&self) -> &Uuid {
                &self.0
            }
        }

        impl fmt::Display for $name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                write!(f, "{}", self.0)
            }
        }

        impl FromStr for $name {
            type Err = uuid::Error;
            fn from_str(s: &str) -> Result<Self, Self::Err> {
                Ok(Self(s.parse::<Uuid>()?))
            }
        }
    };
}

define_id!(VesselId, "Unique identity of an Exoskeleton instance.");
define_id!(TickId, "Identity of a single cognitive tick.");
define_id!(ThreadId, "Identity of a cognitive thread.");
define_id!(PrincipalId, "Identity of a human or agent principal.");
define_id!(EnvelopeId, "Identity of a message envelope.");
define_id!(LedgerEntryId, "Identity of a Relationship Ledger entry.");

/// Content-addressed artifact identity (SHA-256 hex string).
///
/// Computed from the artifact's content bytes. Two artifacts with identical
/// content produce the same `ArtifactId`, enabling deduplication and
/// tamper detection.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct ArtifactId(String);

/// Errors when parsing an [`ArtifactId`] from a string.
#[derive(Debug, thiserror::Error)]
pub enum ArtifactIdError {
    /// The string is not 64 characters long.
    #[error("invalid length: expected 64 hex chars, got {0}")]
    InvalidLength(usize),
    /// The string contains non-hex characters.
    #[error("invalid hex characters")]
    InvalidHex,
}

impl ArtifactId {
    /// Create an ArtifactId by hashing the given content bytes.
    pub fn from_content(content: &[u8]) -> Self {
        Self(sha256_hex(content))
    }

    /// The hex-encoded SHA-256 hash.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for ArtifactId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl FromStr for ArtifactId {
    type Err = ArtifactIdError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        if s.len() != 64 {
            return Err(ArtifactIdError::InvalidLength(s.len()));
        }
        if !s.chars().all(|c| c.is_ascii_hexdigit()) {
            return Err(ArtifactIdError::InvalidHex);
        }
        Ok(Self(s.to_string()))
    }
}

/// Compute the SHA-256 hex digest of arbitrary bytes.
pub fn sha256_hex(data: &[u8]) -> String {
    let hash = Sha256::digest(data);
    format!("{:x}", hash)
}

#[cfg(test)]
mod tests {
    use std::collections::hash_map::DefaultHasher;
    use std::hash::{Hash, Hasher};

    use super::*;

    // ── T-1: Identity Types (UUID-Based) ──

    #[test]
    fn ids_are_unique() {
        let a = VesselId::new();
        let b = VesselId::new();
        assert_ne!(a, b);
    }

    #[test]
    fn id_roundtrips_through_json() {
        let id = TickId::new();
        let json = serde_json::to_string(&id).unwrap();
        let parsed: TickId = serde_json::from_str(&json).unwrap();
        assert_eq!(id, parsed);
    }

    #[test]
    fn id_display_is_uuid() {
        let id = ThreadId::new();
        let s = id.to_string();
        // Must be a valid UUID string
        assert!(
            s.parse::<Uuid>().is_ok(),
            "Display output is not a valid UUID: {s}"
        );
    }

    #[test]
    fn id_from_uuid_roundtrip() {
        let uuid = Uuid::new_v4();
        let id = PrincipalId::from(uuid);
        assert_eq!(*id.as_ref(), uuid);
    }

    #[test]
    fn equal_ids_from_same_uuid() {
        let uuid = Uuid::new_v4();
        let a = EnvelopeId::from(uuid);
        let b = EnvelopeId::from(uuid);
        assert_eq!(a, b);
    }

    #[test]
    fn id_from_str_roundtrip() {
        let id = LedgerEntryId::new();
        let s = id.to_string();
        let parsed: LedgerEntryId = s.parse().unwrap();
        assert_eq!(id, parsed);
    }

    #[test]
    fn id_from_str_rejects_invalid() {
        assert!("not-a-uuid".parse::<VesselId>().is_err());
    }

    #[test]
    fn equal_ids_have_same_hash() {
        let uuid = Uuid::new_v4();
        let a = TickId::from(uuid);
        let b = TickId::from(uuid);

        let hash_of = |id: &TickId| {
            let mut hasher = DefaultHasher::new();
            id.hash(&mut hasher);
            hasher.finish()
        };
        assert_eq!(hash_of(&a), hash_of(&b));
    }

    #[test]
    fn id_default_equals_new() {
        let id = VesselId::default();
        // Default generates a random non-nil UUID
        assert_ne!(*id.as_ref(), Uuid::nil());
    }

    // ── T-2: ArtifactId (Content-Addressed) ──

    #[test]
    fn artifact_id_deterministic() {
        let a = ArtifactId::from_content(b"hello world");
        let b = ArtifactId::from_content(b"hello world");
        assert_eq!(a, b);
    }

    #[test]
    fn artifact_id_different_content() {
        let a = ArtifactId::from_content(b"a");
        let b = ArtifactId::from_content(b"b");
        assert_ne!(a, b);
    }

    #[test]
    fn artifact_id_is_64_hex_chars() {
        let id = ArtifactId::from_content(b"test");
        let s = id.as_str();
        assert_eq!(s.len(), 64);
        assert!(s.chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    fn artifact_id_display() {
        let id = ArtifactId::from_content(b"display test");
        assert_eq!(id.to_string(), id.as_str());
    }

    #[test]
    fn artifact_id_json_roundtrip() {
        let id = ArtifactId::from_content(b"json test");
        let json = serde_json::to_string(&id).unwrap();
        let parsed: ArtifactId = serde_json::from_str(&json).unwrap();
        assert_eq!(id, parsed);
    }

    #[test]
    fn artifact_id_from_str_valid() {
        let hex = "a".repeat(64);
        let id: ArtifactId = hex.parse().unwrap();
        assert_eq!(id.as_str(), hex);
    }

    #[test]
    fn artifact_id_from_str_wrong_length() {
        let result = "abc".parse::<ArtifactId>();
        assert!(matches!(result, Err(ArtifactIdError::InvalidLength(3))));
    }

    #[test]
    fn artifact_id_from_str_invalid_hex() {
        let bad = "g".repeat(64);
        let result = bad.parse::<ArtifactId>();
        assert!(matches!(result, Err(ArtifactIdError::InvalidHex)));
    }

    #[test]
    fn sha256_hex_known_value() {
        let hash = sha256_hex(b"hello world");
        assert_eq!(
            hash,
            "b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9"
        );
    }
}
